<!-- Travis badge -->
<img src="https://cloud.drone.io/api/badges/moleculer-go/moleculer/status.svg" />

<!-- Coveralls badge -->
<img src="https://coveralls.io/repos/github/moleculer-go/moleculer/badge.svg?branch=develop" />

<!-- Code Climate badge -->
<a href="https://codeclimate.com/github/moleculer-go/moleculer/maintainability">
    <img src="https://api.codeclimate.com/v1/badges/514bcfed231e0e74c087/maintainability" />
</a>

<!-- Go report card -->
<a href="https://goreportcard.com/report/github.com/moleculer-go/moleculer" rel="nofollow">
    <img src="https://goreportcard.com/badge/github.com/moleculer-go/moleculer" alt="Go Report Card" data-canonical-src="https://goreportcard.com/badge/github.com/moleculer-go/moleculer" style="max-width:100%;">
</a>

<!-- fossa -->
<a href="https://app.fossa.io/projects/git%2Bgithub.com%2Fmoleculer-go%2Fmoleculer?ref=badge_shield" rel="nofollow">
    <img src="https://app.fossa.io/api/projects/git%2Bgithub.com%2Fmoleculer-go%2Fmoleculer.svg?type=shield" alt="Ffossa Status"  style="max-width:100%;">
</a>

