title: Moleculer Go - Progressive microservices framework in Go
subtitle: "Progressive microservices framework in Go"
description: "Moleculer is a progressive microservices framework in Go"
author: MoleculerGO
language: en
timezone: UTC
url: https://gomicro.services
github_edit_link: https://github.com/moleculer-go/site/edit/master/source/
root: /
permalink: news/:year/:month/:day/:title/
#archive_dir: news
code_dir: downloads/code
#new_post_name: :year-:month-:day-:title.md # File name of new posts
#post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: moleculer
# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

#deploy:
#  type: git
#  repo: git@github.com:moleculer-go/moleculerjs.github.io.git

# disqus_shortname: moleculer
google_analytics: UA-99099811-1
# fb_admins: 100000247608790
algolia:
  en:
    api_key: xyz
    index_name: moleculer_web

twitter: MoleculerG
github: moleculer-go/moleculer
stackoverflow: questions/tagged/moleculer-go

alias:
  docs/benchmark.html: docs/0.1/benchmark.html
  docs/broker.html: docs/0.1/broker.html
  docs/cachers.html: docs/0.1/cachers.html
  docs/circuit-breaker.html: docs/0.1/circuit-breaker.html
  docs/context.html: docs/0.1/context.html
  docs/contributing.html: docs/0.1/contributing.html
  docs/docker.html: docs/0.1/docker.html
  docs/errors.html: docs/0.1/errors.html
  docs/examples.html: docs/0.1/examples.html
  docs/faq.html: docs/0.1/faq.html
  docs/logger.html: docs/0.1/logger.html
  docs/metrics.html: docs/0.1/metrics.html
  docs/modules.html: docs/0.1/modules.html
  docs/moleculer-cli.html: docs/0.1/moleculer-cli.html
  docs/moleculer-repl.html: docs/0.1/moleculer-repl.html
  docs/gateway.html: docs/0.1/gateway.html
  docs/nodes.html: docs/0.1/nodes.html
  docs/runner.html: docs/0.1/runner.html
  docs/serializers.html: docs/0.1/serializers.html
  docs/serverless.html: docs/0.1/serverless.html
  docs/service-registry.html: docs/0.1/service-registry.html
  docs/service.html: docs/0.1/service.html
  docs/statistics.html: docs/0.1/statistics.html
  docs/support.html: support.html
  docs/transporters.html: docs/0.1/transporters.html
  docs/usage.html: docs/0.1/usage.html
  docs/validation.html: docs/0.1/validation.html

  0.12/docs/support.html: support.html
  0.12/docs/modules.html: modules.html

  0.12/docs/benchmark.html: docs/0.1/benchmark.html
  0.12/docs/broker.html: docs/0.1/broker.html
  0.12/docs/cachers.html: docs/0.1/cachers.html
  0.12/docs/circuit-breaker.html: docs/0.1/circuit-breaker.html
  0.12/docs/context.html: docs/0.1/context.html
  0.12/docs/contributing.html: docs/0.1/contributing.html
  0.12/docs/docker.html: docs/0.1/docker.html
  0.12/docs/errors.html: docs/0.1/errors.html
  0.12/docs/examples.html: docs/0.1/examples.html
  0.12/docs/faq.html: docs/0.1/faq.html
  0.12/docs/logger.html: docs/0.1/logger.html
  0.12/docs/metrics.html: docs/0.1/metrics.html
  0.12/docs/moleculer-cli.html: docs/0.1/moleculer-cli.html
  0.12/docs/moleculer-repl.html: docs/0.1/moleculer-repl.html
  0.12/docs/gateway.html: docs/0.1/gateway.html
  0.12/docs/nodes.html: docs/0.1/nodes.html
  0.12/docs/runner.html: docs/0.1/runner.html
  0.12/docs/serializers.html: docs/0.1/serializers.html
  0.12/docs/serverless.html: docs/0.1/serverless.html
  0.12/docs/service-registry.html: docs/0.1/service-registry.html
  0.12/docs/service.html: docs/0.1/service.html
  0.12/docs/statistics.html: docs/0.1/statistics.html
  0.12/docs/transporters.html: docs/0.1/transporters.html
  0.12/docs/usage.html: docs/0.1/usage.html
  0.12/docs/validation.html: docs/0.1/validation.html

  api/context.html: api/0.12/context.html
  api/protocol.html: api/0.12/protocol.html
  api/service-broker.html: api/0.12/service-broker.html
  api/service.html: api/0.12/service.html

  docs/index.html: docs/0.1/index.html
  api/index.html: docs/0.1/index.html
